const assert = require('assert')
const { findUserByEmail, findUserById } = require('../async')

describe('The async tests',() => {
    describe('findUserById',() => {
        it('should return found user data by id', () => {
            return findUserById(1).then( result => {
                assert.equal(result.user.name, 'trav')
            })
        })
        it('should throw an error if user was not found', () => {
            return findUserById(9).catch(error => {
                assert.equal(error.message, 'User with id: 9 was not found.')
            })
        })
        it('should return found user data by id', () => {
            return findUserById(1).catch(error => {
                assert.equal(result.user.name, 'trav')
            })
        })
    })
    describe('findUserByEmail',() => {
        it('should return found user data by email', () => {
            return findUserByEmail('trav@gmail.com').then( result => {
                assert.equal(result.user.name, 'trav')
            })
        })
        it('should throw error if user was not found by email', () => {
            try {
                const result = await findUserByEmail('s@gmail.com')
                assert.fail('EXPECTED_ERROR')
            } catch (error) {
                assert.equal(error.message, 'User with email: s@gmail.com was not found.')
            }
        })
    })
})